# Generated by Django 6.0.5 on 2026-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(default='', max_length=255)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('ats_score', models.IntegerField(default=0)),
                ('ats_breakdown', models.JSONField(blank=True, default=dict)),
                ('job_matches', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
